<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'k-tet',
                'name' => 'K-TET',
                'mrp' => 500,
                'sr' => 500,
                'image' => 'default.jpg',
                'description' => 'Psychology, Philosophy, Pedagogy, Pyq, 500 most repeated questions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'vijayamanthram-4th-edition',
                'name' => 'VIJAYAMANTHRAM(4th edition)',
                'mrp' => 500,
                'sr' => 400,
                'image' => 'default.jpg',
                'description' => 'Special topics related to devaswom board exams, 35 sets of model questions, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'samagra-visakalanam-3volume',
                'name' => 'SAMAGRA VISAKALANAM(3volume)',
                'mrp' => 1500,
                'sr' => 1500,
                'image' => 'default.jpg',
                'description' => '2021-2023 psc pyq with explanation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'psc-capsule',
                'name' => 'PSC CAPSULE',
                'mrp' => 150,
                'sr' => 150,
                'image' => 'default.jpg',
                'description' => 'Keralam - bharanavum bharana samvidhanangalum, supradana niyamangal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'samagra-padyasala',
                'name' => 'SAMAGRA PADYASALA',
                'mrp' => 400,
                'sr' => 400,
                'image' => 'default.jpg',
                'description' => '5-10 SCERT text, teachers book question pool, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'current-affairs',
                'name' => 'CURRENT AFFAIRS',
                'mrp' => 250,
                'sr' => 250,
                'image' => 'default.jpg',
                'description' => '2022-2024 complete current affairs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'malsara-pareekshakalil-english',
                'name' => 'MALSARA PAREEKSHAKALIL ENGLISH',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => 'Grammar & vocabulary with pyq & explanation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'math-spark',
                'name' => 'MATH SPARK',
                'mrp' => 400,
                'sr' => 400,
                'image' => 'default.jpg',
                'description' => '1700 practice questions with explanation, topic wise questions, shortcuts, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => '10th-screening-test-2nd-edition',
                'name' => '10TH SCREENING TEST (2nd edition)',
                'mrp' => 300,
                'sr' => 300,
                'image' => 'default.jpg',
                'description' => 'Important questions & answers on the basis of 10th prelims syllabus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'malsara-pareekshakalil-malayalam',
                'name' => 'MALSARA PAREEKSHAKALIL MALAYALAM',
                'mrp' => 260,
                'sr' => 260,
                'image' => 'default.jpg',
                'description' => 'Grammar & vocabulary with pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'ncert-samagra-plus',
                'name' => 'NCERT SAMAGRA PLUS',
                'mrp' => 250,
                'sr' => 250,
                'image' => 'default.jpg',
                'description' => 'Constitution, politics, civics notes on the basis of +1, +2 NCERT text, teachers note, question pool, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'ncert-scert-economics',
                'name' => 'NCERT - SCERT ECONOMICS',
                'mrp' => 50,
                'sr' => 50,
                'image' => 'default.jpg',
                'description' => 'Question pool - statement questions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'exam-helper',
                'name' => 'EXAM HELPER',
                'mrp' => 300,
                'sr' => 300,
                'image' => 'default.jpg',
                'description' => 'Questions & answers in psc new pattern exams',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'devaswom-board-sub-group-officer-grade',
                'name' => 'DEVASWOM BOARD SUB GROUP OFFICER GRADE',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => 'Devaswom board special topic, gk, english, current affairs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'keralam-lgs-muthal-ldc-vare',
                'name' => 'KERALAM LGS MUTHAL LDC VARE',
                'mrp' => 0,
                'sr' => 0,
                'image' => 'default.jpg',
                'description' => 'All facts related to Keralam (history, politics, renaissance, economics)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'university-assistant-prelims-mains',
                'name' => 'UNIVERSITY ASSISTANT PRELIMS &MAINS',
                'mrp' => 350,
                'sr' => 350,
                'image' => 'default.jpg',
                'description' => 'Model exams & explanations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'driver-rank-file-latest-edition',
                'name' => 'DRIVER RANK FILE (latest edition)',
                'mrp' => 150,
                'sr' => 150,
                'image' => 'default.jpg',
                'description' => 'Driver special topic & pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'psc-pareeksha-sahayi',
                'name' => 'PSC PAREEKSHA SAHAYI',
                'mrp' => 220,
                'sr' => 220,
                'image' => 'default.jpg',
                'description' => '10000 psc pyq on the basis of lgs syllabus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'current-affairs-2023',
                'name' => 'CURRENT AFFAIRS 2023',
                'mrp' => 300,
                'sr' => 300,
                'image' => 'default.jpg',
                'description' => 'All current affairs in 2023, 2022, 2021',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'current-affairs-2022',
                'name' => 'CURRENT AFFAIRS 2022',
                'mrp' => 150,
                'sr' => 150,
                'image' => 'default.jpg',
                'description' => 'All current affairs in 2020, 2021, 2022',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'devaswom-board-pareeksha-sahayi-peon-strong-room-guard',
                'name' => 'DEVASWOM BOARD PAREEKSHA SAHAYI PEON & STRONG ROOM GUARD',
                'mrp' => 200,
                'sr' => 200,
               'image' => 'default.jpg',
                'description' => 'Special topic, gk, english, maths pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'high-court-assistant',
                'name' => 'HIGH COURT ASSISTANT',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => '1000 maths pyq with explanation, 2000 english pyq, malayalam, psc deleted questions & answers, current affairs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'cpo-special-topics',
                'name' => 'CPO SPECIAL TOPICS',
                'mrp' => 0,
                'sr' => 0,
                'image' => 'default.jpg',
                'description' => 'Special topic, expected questions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'cpo-special-topics-2-level',
                'name' => 'CPO SPECIAL TOPICS +2 LEVEL',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => 'All special topics related to cpo exams',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'indian-samsthanavum-kendra-bharana-predesangalum',
                'name' => 'INDIAN SAMSTHANAVUM KENDRA BHARANA PREDESANGALUM',
                'mrp' => 125,
                'sr' => 125,
                'image' => 'default.jpg',
                'description' => 'All facts about Indian states & union territory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'degree-prelims-2022',
                'name' => 'DEGREE PRELIMS 2022',
                'mrp' => 0,
                'sr' => 0,
                'image' => 'default.jpg',
                'description' => 'Questions with explanation of stage 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'driver-rank-file-latest-edition-samagra-pareeksha-sahayi',
                'name' => 'DRIVER RANK FILE (LATEST EDITION)SAMAGRA PAREEKSHA SAHAYI',
                'mrp' => 290,
                'sr' => 290,
                'image' => 'default.jpg',
                'description' => 'Special topics, pyq, gk, current affairs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => '3-in-1',
                'name' => '3 IN 1',
                'mrp' => 120,
                'sr' => 120,
                'image' => 'default.jpg',
                'description' => 'IT & cyber law, constitution, social welfare schemes for degree level exams',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'samagra-padyasala-2',
                'name' => 'SAMAGRA PADYASALA',
                'mrp' => 400,
                'sr' => 400,
                'image' => 'default.jpg',
                'description' => '5-10 scert text, teachers book, question pool, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'maths-work-book',
                'name' => 'MATHS WORK BOOK',
                'mrp' => 0,
                'sr' => 0,
                'image' => 'default.jpg',
                'description' => '1200 maths practice questions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'psc-driver',
                'name' => 'PSC DRIVER',
                'mrp' => 100,
                'sr' => 100,
                'image' => 'default.jpg',
                'description' => 'Special topics, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'final-step-for-first-rank',
                'name' => 'FINAL STEP FOR FIRST RANK',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => '12000 previous gk, maths, english',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'science-psc',
                'name' => 'SCIENCE PSC',
                'mrp' => 160,
                'sr' => 160,
               'image' => 'default.jpg',
                'description' => 'Physics, chemistry, biology pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'university-assistant-psc-previous-questions',
                'name' => 'UNIVERSITY ASSISTANT PSC PREVIOUS QUESTIONS',
                'mrp' => 400,
                'sr' => 400,
                'image' => 'default.jpg',
                'description' => 'Maths, english, malayalam, 12000 gk',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'lastgrade-psc-pareeksha-sahayi',
                'name' => 'LASTGRADE PSC PAREEKSHA SAHAYI',
                'mrp' => 250,
                'sr' => 250,
               'image' => 'default.jpg',
                'description' => 'Gk & maths (pyq) lgs syllabus basis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'ld-typist-computer-assistant',
                'name' => 'LD TYPIST COMPUTER ASSISTANT',
                'mrp' => 200,
                'sr' => 200,
                'image' => 'default.jpg',
                'description' => 'Special topic, explanation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'information-technology-cyber-law',
                'name' => 'INFORMATION TECHNOLOGY&CYBER LAW',
                'mrp' => 150,
                'sr' => 150,
                'image' => 'default.jpg',
                'description' => 'IT & cyber law, pyq',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'publisher_id' => 1,
                'cat_id' => 1,
                'slug' => 'degree-mains-special-topics',
                'name' => 'DEGRE MAINS SPECIAL TOPICS',
                'mrp' => 300,
                'sr' => 300,
                'image' => 'default.jpg',
                'description' => 'Special topic of SI, APO, Excise inspector',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($items as $item) {
            Item::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
